### ISSUE TITLE
_ember_jquery when enabled

### ISSUE THREAD

**Issue by exetico** [angusmcleod/layouts-profile#2]
Hi,

Currenlty i get an error when i'm visiting other pages than the frontpage.
![image](https://user-images.githubusercontent.com/3549445/30333463-4bd721a8-97dd-11e7-8067-8468b120fa29.png)
I'm on the latest version of this - and the layouts, including Discourse itselfe.
No widget is generated at forum-section:
![image](https://user-images.githubusercontent.com/3549445/30333529-6ea30b2a-97dd-11e7-9f1d-665c274e16db.png)
Example from frontpage:
![image](https://user-images.githubusercontent.com/3549445/30333546-779d576c-97dd-11e7-8b97-6af387f5ba7d.png)
This setup is running on localhost with docker.

If i disable this widget, no error shows up :-)

**Comment by angusmcleod** [comment]
@exetico Thanks for reporting this. Fixed:
https://github.com/angusmcleod/discourse-profile-widget/commit/31cca6d297d1e31b362cb1db44b1202b21bef68e
